version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

conda:
   file: docs/environment.yml

python:
   version: 3.8
   install:
      - method: setuptools
        path: .

submodules:
   include: all

sphinx:
  fail_on_warning: true