version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

conda:
   environment: docs/environment.yml

python:
   install:
   - requirements: requirements.txt

submodules:
   include: all

sphinx:
  fail_on_warning: true