channels:
- conda-forge
dependencies:
- python==3.8
- pandas==1.5.3
- matplotlib==3.6.1
- numpy==1.23.3
- pip
- pip:
  - git+https://github.com/Open-Earth-Foundation/OpenClimate-pyclient.git#egg=oc_pyclient
