name: openclimate_docs
dependencies:
   - python=3.9
   # If your docs code examples depend on other packages add them here
   - numpy
   - pandas
   - matplotlib
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - Jinja2
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
     - recommonmark
     - ipython_genutils